clear;
clc;
close all;

%% ===========================
% Mission
% ===========================

start = [0 0 -10];

target = [0 25 -10];

%% ===========================
% Multiple Obstacles
% [NorthMin NorthMax EastMin EastMax]
% ===========================

obstacles = [
    -3 3 4 8;
    -3 3 11 15;
    -3 3 18 22
    ];

%% ===========================
% Adaptive Context
% ===========================

battery = 85;
windSpeed = 4;
missionPriority = 0.9;

context = detectContext( ...
    battery,...
    windSpeed,...
    3);

weights = contextManager( ...
    context,...
    missionPriority);

decision = decisionManager(context);

%% ===========================
% Initial Conditions
% ===========================

currentPosition = start;

actualPath = currentPosition;

replanCount = 0;

%% ===========================
% Figure
% ===========================

figure;

hold on;
grid on;
axis equal;

xlabel("East (m)");
ylabel("North (m)");

title("Adaptive Multi-Obstacle UAV Path Planning");

%% Obstacles

for i = 1:size(obstacles,1)

    b = obstacles(i,:);

    rectangle( ...
        "Position",[ ...
        b(3),...
        b(1),...
        b(4)-b(3),...
        b(2)-b(1)],...
        "FaceColor",[0.8 0.2 0.2],...
        "EdgeColor","k");

    text( ...
        mean([b(3) b(4)]),...
        mean([b(1) b(2)]),...
        sprintf("Obstacle %d",i),...
        "HorizontalAlignment","center");

end

%% Direct path

plot( ...
    [start(2) target(2)],...
    [start(1) target(1)],...
    "k--",...
    "LineWidth",1.5);

%% Start and target

plot( ...
    start(2),...
    start(1),...
    "ko",...
    "MarkerFaceColor","g",...
    "MarkerSize",9);

plot( ...
    target(2),...
    target(1),...
    "ko",...
    "MarkerFaceColor","b",...
    "MarkerSize",9);

%% ===========================
% Adaptive Planning
% ===========================

[path,info] = multiObstaclePlanner( ...
    currentPosition,...
    target,...
    obstacles,...
    weights,...
    decision.speed);

fprintf("\n============================\n");
fprintf("MULTI-OBSTACLE EXPERIMENT\n");
fprintf("============================\n");

if info.directBlocked

    fprintf("Direct Path       : BLOCKED\n");

    for i = 1:numel(info.candidateNames)

        fprintf( ...
            "%s | Distance %.2f m | Clearance %.2f m | Cost %.3f\n",...
            info.candidateNames(i),...
            info.candidateDistance(i),...
            info.candidateClearance(i),...
            info.candidateCosts(i));

    end

    fprintf( ...
        "Selected Detour   : %s\n",...
        info.candidateNames(info.bestIndex));

    fprintf( ...
        "Selected Distance : %.2f m\n",...
        info.distance);

    fprintf( ...
        "Selected Time     : %.2f s\n",...
        info.time);

    fprintf( ...
        "Selected Clearance: %.2f m\n",...
        info.clearance);

else

    fprintf("Direct Path       : CLEAR\n");

end

fprintf("============================\n");

%% Plot selected adaptive route

plot( ...
    path(:,2),...
    path(:,1),...
    "r--",...
    "LineWidth",3);

%% ===========================
% Follow Path
% ===========================

for i = 2:size(path,1)

    plot( ...
        path(i-1:i,2),...
        path(i-1:i,1),...
        "b-",...
        "LineWidth",3);

end

actualPath = path;

%% ===========================
% Final Results
% ===========================

totalDistance = ...
    sum(vecnorm(diff(actualPath(:,1:2),1,1),2,2));

totalTime = ...
    totalDistance/max(decision.speed,eps);

minimumClearance = ...
    info.clearance;

fprintf("\n================================\n");
fprintf("FINAL MULTI-OBSTACLE RESULT\n");
fprintf("================================\n");

fprintf("Detour Used       : YES\n");

fprintf("Selected Route    : %s\n",...
    info.candidateNames(info.bestIndex));

fprintf("Total Distance    : %.2f m\n",...
    totalDistance);

fprintf("Estimated Time    : %.2f s\n",...
    totalTime);

fprintf("Minimum Clearance : %.2f m\n",...
    minimumClearance);

fprintf("Final Position    : [%.2f %.2f %.2f]\n",...
    actualPath(end,1),...
    actualPath(end,2),...
    actualPath(end,3));

fprintf("================================\n");

legend( ...
    "Obstacle 1",...
    "Obstacle 2",...
    "Obstacle 3",...
    "Direct Path",...
    "Start",...
    "Target",...
    "Selected Adaptive Route",...
    "Actual UAV Route",...
    "Location","best");

hold off;